# Convert Slot Table csv to json

this is done to minimize load on the API infrastructure, given that the slot table itself is just a constant dump of all positions in different coordinate systems along with their static information.


To reproduce:

download the Slots from https://nginx-hgtddb.app.cern.ch/partslist

and the Slot attributes from https://nginx-hgtddb.app.cern.ch/listattributes  
(keep only these columns: `part_serial_number,FT_Length_mm,FT_length_category,DU_F_or_B,Layer,Module,Used_for_NTC_Interlock,PEB_type,Quadrant,Row,SU_Module,SU_Row,SU_type,Disk_per_vessel,Disk_side_from_IP,Vessel`)

saving both as csv.

The csv needs to be prepared to only include `,` (no `;`) and no trailing spaces in the header row.

Then you can read them in again and export as json, mimicking a successful API GET request.

In [1]:
import pandas as pd

In [2]:
fields = ['part_serial_number','FT_Length_mm','FT_length_category','DU_F_or_B','Layer','Module','Used_for_NTC_Interlock','PEB_type','Quadrant','Row','SU_Module','SU_Row','SU_type','Disk_per_vessel','Disk_side_from_IP','Vessel']

In [3]:
csv_file = pd.DataFrame(pd.read_csv("Slot_Table_fullJuly2026_withPreliminaryNTC.csv", sep = ",", header = 0, index_col = False, usecols=fields))

In [4]:
csv_file

,part_serial_number,DU_F_or_B,Disk_per_vessel,Disk_side_from_IP,FT_Length_mm,FT_length_category,Layer,Module,PEB_type,Quadrant,Row,SU_Module,SU_Row,SU_type,Used_for_NTC_Interlock,Vessel
0,V2:L2:Q1:R9:M6,B,Back,front,236.6,51,2,6,3B,1,9,2,2,BO05,Interlock,2
1,V2:L2:Q1:R9:M5,B,Back,front,195.4,54,2,5,3B,1,9,1,2,BO05,DCS_only,2
2,V2:L2:Q1:R9:M4,B,Back,front,154.3,56,2,4,3B,1,9,4,2,BO04,DCS_only,2
3,V2:L2:Q1:R9:M3,B,Back,front,113.1,58,2,3,3B,1,9,3,2,BO04,DCS_only,2
4,V2:L2:Q1:R9:M2,B,Back,front,71.8,60,2,2,3B,1,9,2,2,BO04,Interlock,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8371,VD:L0:Q0:R2:M16,F,Front,front,582.2,7,0,16,1F,0,2,2,2,FI01,NaN,D
8372,VD:L0:Q0:R2:M11,F,Front,front,412.9,41,0,11,1F,0,2,2,2,FM01,NaN,D
8373,VD:L0:Q0:R2:M10,F,Front,front,377.9,22,0,10,1F,0,2,1,2,FM01,NaN,D
8374,VD:L0:Q0:R2:M9,F,Front,front,342.2,44,0,9,1F,0,2,4,2,FM02,NaN,D
8375,VD:L0:Q0:R2:M12,F,Front,front,447.9,39,0,12,1F,0,2,3,2,FM01,NaN,D

In [5]:
csv_file.to_json("Slot_Table_fullJuly2026_withPreliminaryNTC.json", orient = "records", force_ascii = True, default_handler = None)

In [6]:
csv_file_ = pd.DataFrame(pd.read_csv("Slot_fullJuly2026_withPreliminaryNTC.csv", sep = ",", header = 0, index_col = False))

In [7]:
csv_file_

,Part ID,Serial #,Version,Name Label,KindOfPart,Location,Manufacturer,Comments,User,Action
0,31191,VM:L1:Q0:R4:M12,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
1,31385,VM:L1:Q0:R21:M1,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
2,31384,VM:L1:Q0:R21:M2,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
3,31383,VM:L1:Q0:R21:M3,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
4,31382,VM:L1:Q0:R21:M4,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
...,...,...,...,...,...,...,...,...,...,...
8371,16438,V2:L0:Q0:R18:M3,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8372,16439,V2:L0:Q0:R18:M2,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8373,16440,V2:L0:Q0:R18:M1,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8374,16441,V2:L0:Q0:R19:M18,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8375,16442,V2:L0:Q0:R19:M17,NaN,NaN,Slot,CERN-ATLAS (somewhere),ProdDB-Virtual Manufacturer,NaN,anstein,NaN

In [8]:
csv_file_.to_json("Slot_fullJuly2026_withPreliminaryNTC.json", orient = "records", force_ascii = True, default_handler = None)