# Convert Slot Table csv to json

this is done to minimize load on the API infrastructure, given that the slot table itself is just a constant dump of all positions in different coordinate systems along with their static information

In [1]:
import pandas as pd

In [2]:
csv_file = pd.DataFrame(pd.read_csv("Slot_Table_fullJune2025_demo54mod.csv", sep = ",", header = 0, index_col = False))

In [3]:
csv_file

,part_serial_number,FT_Length_mm,FT_length_category,F_or_B,Layer,Module,PEB_type,Quadrant,Row,SU_Module,SU_Row,SU_type,Vessel
0,V2:L2:Q1:R9:M7,277.7,47,B,2,7,3B,1,9,3,2,BO05,2
1,V2:L2:Q1:R9:M6,236.6,51,B,2,6,3B,1,9,2,2,BO05,2
2,V2:L2:Q1:R9:M5,195.4,54,B,2,5,3B,1,9,1,2,BO05,2
3,V2:L2:Q1:R9:M4,154.3,56,B,2,4,3B,1,9,4,2,BO04,2
4,V2:L2:Q1:R9:M3,113.1,58,B,2,3,3B,1,9,3,2,BO04,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8081,VD:L0:Q0:R3:M17,608.4,5,F,0,17,1F,0,3,3,3,FI01,D
8082,VD:L0:Q0:R3:M16,576.1,8,F,0,16,1F,0,3,2,3,FI01,D
8083,VD:L0:Q0:R3:M15,544.0,11,F,0,15,1F,0,3,1,3,FI01,D
8084,VD:L0:Q0:R3:M14,511.9,14,F,0,14,1F,0,3,5,3,FM01,D
8085,VD:L0:Q0:R3:M13,476.5,38,F,0,13,1F,0,3,4,3,FM01,D

In [6]:
csv_file.to_json("Slot_fullJune2025_demo54mod.json", orient = "records", force_ascii = True, default_handler = None)

In [7]:
csv_file_ = pd.DataFrame(pd.read_csv("Slot_fullJune2025_demo54mod.csv", sep = ",", header = 0, index_col = False))

In [8]:
csv_file_

,Part ID,Serial #,Barcode,Version,Name Label,KindOfPart,Manufacturer,Comments,User,Action
0,30655,VD:L0:Q0:R1:M18,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
1,30708,VD:L0:Q0:R3:M1,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
2,30707,VD:L0:Q0:R3:M2,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
3,30706,VD:L0:Q0:R3:M3,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
4,30705,VD:L0:Q0:R3:M4,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
...,...,...,...,...,...,...,...,...,...,...
8081,16438,V2:L0:Q0:R18:M3,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8082,16439,V2:L0:Q0:R18:M2,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8083,16440,V2:L0:Q0:R18:M1,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8084,16441,V2:L0:Q0:R19:M18,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN
8085,16442,V2:L0:Q0:R19:M17,NaN,NaN,NaN,Slot,ProdDB-Virtual Manufacturer,NaN,anstein,NaN

In [9]:
csv_file_.to_json("Slot_fullJune2025_demo54mod.json", orient = "records", force_ascii = True, default_handler = None)